Update objetivo5-bash.yml

diff --git a/.github/workflows/objetivo5-bash.yml b/.github/workflows/objetivo5-bash.yml
--- a/.github/workflows/objetivo5-bash.yml
+++ b/.github/workflows/objetivo5-bash.yml
@@ -15,3 +15,9 @@ jobs:
       - name: Login en Azure (Bash)
         run: | 
           az login --username ${{ secrets.AZ_USERNAME }} -- password $ secrets.AZ_PASS }}
+          if [ $? -eq 0 ]; then
+            echo "Azure login successful!"
+          else
+            echo "Azure login failed!"
+            exit 1
+          fi
